'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    ru: {
        // Настройки
        settings: 'Настройки',
        darkTheme: 'Тёмная тема',
        lightTheme: 'Светлая тема',
        help: 'Помощь',
        color: 'Цвет',
        language: 'Смена языка',
        tutorial: 'Пройти обучение',
        share: 'Поделиться',
        selectColor: 'Выберите цвет',
        close: 'Закрыть',
        
        // Профиль
        pts: 'pts',
        todayGoals: 'Цели на сегодня',
        generate: 'Сгенерировать',
        yesterday: 'Вчера',
        series: 'Серия',
        days: 'дн.',
        
        // Цели
        goals: 'Цели',
        completed: 'Завершенные',
        inProgress: 'В процессе',
        available: 'Доступные',
        sport: 'Спорт',
        discipline: 'Дисциплина',
        spirituality: 'Духовность',
        selfDevelopment: 'Саморазвитие',
        
        // Достижения
        myAchievements: 'Мои',
        allAchievements: 'Все',
        common: 'Обычные',
        rare: 'Редкие',
        legendary: 'Легендарные',
        epic: 'Эпические',
        
        // Общие
        copy: 'Скопировать',
        loading: 'Загрузка...',
        error: 'Ошибка',
        success: 'Успешно',
        ready: 'Готово!',
        generating: 'Генерируем отчёт',
        reportCopied: 'Отчёт скопирован!',
        loadingUser: 'Загрузка данных пользователя...',
        loadingGoals: 'Загрузка целей пользователя...',
        loadingAchievements: 'Загрузка достижений пользователя...',
        yesterdayGoals: 'Вчерашние цели',
        generateReport: 'Сгенерировать отчёт',
        completingGoal: 'Выполняем цель...',
        goalCompleted: 'Цель успешно выполнена!',
        cancelingGoal: 'Отменяем выполнение цели...',
        goalCanceled: 'Успешно отменено выполнение!',
        goalError: 'Ошибка при выполнении цели:',
        goalErrorRetry: 'Не удалось выполнить цель. Попробуйте снова.',
        goalMoveError: 'Ошибка при перемещении цели:',
        goalMoveErrorRetry: 'Не удалось переместить цель в раздел \'В процессе\'. Попробуйте снова.',
        rollback: 'Откат',
        back: 'Вернуться',
        noGoalsYesterday: 'У вас нет таких целей',
        goalMoved: 'Цель успешно перемещена в раздел \'В процессе\'!',
        goalRemoved: 'Цель успешно убрана!',
        goalRemoveError: 'Ошибка при убирании цели:',
        goalRemoveErrorRetry: 'Не удалось убрать цель. Попробуйте снова.',
        takingGoal: 'Взять цель...',
        goalTaken: 'Цель успешно взята на',
        goalTakenDays: 'дней!',
        goalTakeError: 'Ошибка при взятии цели:',
        goalTakeErrorRetry: 'Не удалось взять цель. Попробуйте снова.',
        // ModalWindowNewGoals
        addCustomGoal: 'Добавить свою цель',
        addCustomGoalInfo: 'Заполнив все поля вы можете добавить свою цель, которая будет только у вас',
        goalTitle: 'Название цели',
        goalTitlePlaceholder: 'Введите название цели',
        goalCategory: 'Категория цели',
        adding: 'Добавление...',
        addGoal: 'Добавить цель',
        addGoalError: 'Ошибка при добавлении цели:',
        addGoalErrorRetry: 'Не удалось добавить цель. Попробуйте еще раз.',
        // ModalWindowMe
        openInTelegram: 'Открой Mini App в Telegram',
        noData: 'Нет данных',
        cardReady: 'Карточка готова!',
        generationError: 'Ошибка генерации',
        generateCard: 'Сгенерируй карточку',
        telegramApiNotFound: 'Telegram API не найден',
        preparingImage: 'Подготавливаем картинку для Stories...',
        uploadFailed: 'Не удалось загрузить',
        noUploadTempUrl: 'Нет uploadTempUrl',
        storiesOpened: 'Открылось окно Stories с кнопкой!',
        storiesUnavailable: 'Истории с кнопкой недоступны. Скачиваем...',
        downloaded: 'Скачано! Добавь в историю вручную и вставь ссылку стикером',
        shareFailed: 'Не удалось поделиться в Stories',
        generatingImage: 'Генерируем изображение',
        shareStory: '📤 Поделиться/история',
        shareCaption: 'Вы тоже можете получить такую ачивку\nhttps://t.me/BotMotivation_TG_bot \nПереходи в бота выполняй свои цели и получай ачивки',
        botName: 'Бот «Дневные достижения»',
        // LoadingScreen
        welcome: 'ДОБРО ПОЖАЛОВАТЬ,',
        warrior: 'Воин дисциплины',
        loadingGoals: 'Идёт загрузка целей...',
        // About
        next: 'Далее',
        // Achievements
        achievements: 'Ачивки',
        newAchievement: 'Вы получили новое достижение!',
        howToGetAchievement: 'Как получить ачивку:',
        achievementWillBeAdded: '• Ачивка сама будет к вам добавлена',
        user: 'Пользователь',
        // Goals
        noSuchGoals: 'У вас нет таких целей',
        removeGoal: 'Убрать цель',
        takeGoalFor: 'Взять цель на',
        days120: '120 дней',
        days60: '60 дней',
        days30: '30 дней',
        // Lights / Milestones
        seriesFire: 'Огонёк серии',
        continue: 'Продолжить',
        milestone2Title: 'Серия началась!',
        milestone2Subtitle: 'Постарайся её не потерять',
        milestone5Title: 'Ты в ритме 👏',
        milestone5Subtitle: 'Продолжай держать темп',
        milestone10Title: 'Красавчик!',
        milestone10Subtitle: 'Ты держишь серию уже 10 дней',
        milestone30Title: 'Это уже привычка',
        milestone30Subtitle: '30 дней подряд — серьёзно',
        milestone60Title: 'Стабильность 🔥',
        milestone60Subtitle: 'Ты на другом уровне',
        milestone100Title: 'Легендарно',
        milestone100Subtitle: '100 дней — это мощно',
        milestone120Title: 'Абсолютная дисциплина',
        milestone120Subtitle: 'Ты машина',
        // Обучение (главный экран)
        tutorialIntroTitle: 'Обучение',
        tutorialIntroDesc: 'Сейчас вы пройдёте небольшой курс обучения. За него вы узнаете, как пользоваться приложением, возьмёте себе свою первую цель, научитесь их выполнять, сгенерируете дневной отчёт и узнаете, что зачем нужно.',
        tutorialIntroButton: 'Начать обучение',
        tutorialStepPoints: 'Очки',
        tutorialStepPointsDesc: 'Это ваши очки за выполненные цели. Чем больше целей вы закрываете, тем больше очков получаете — они показывают ваш прогресс и помогают расти по уровням.',
        tutorialStepLevel: 'Уровень',
        tutorialStepLevelDesc: 'Здесь видно ваш текущий уровень и шкалу до следующего. Уровень растёт от очков: выполняйте цели регулярно, чтобы подниматься выше.',
        tutorialStepProfile: 'Профиль',
        tutorialStepProfileDesc: 'Ваше имя и «серия» — сколько дней подряд вы выполняли цели.',
        tutorialStepSettingsButton: 'Кнопка настроек',
        tutorialStepSettingsButtonDesc: 'Нажмите на эту кнопку — откроется окно настроек. Там можно сменить тему, язык, цвет и многое другое.',
        tutorialStepSettingsTheme: 'Тема',
        tutorialStepSettingsThemeDesc: 'Переключатель светлой и тёмной темы. Выберите, как вам удобнее.',
        tutorialStepSettingsHelp: 'Помощь',
        tutorialStepSettingsHelpDesc: 'Открывает бота в Telegram для связи с поддержкой и вопросов.',
        tutorialStepSettingsColor: 'Цвет',
        tutorialStepSettingsColorDesc: 'Здесь можно выбрать цвет акцента приложения — кнопки и выделения будут этого цвета.',
        tutorialStepSettingsColorChoose: 'Выберите цвет, который вам нравится.',
        tutorialStepSettingsLanguage: 'Язык',
        tutorialStepSettingsLanguageDesc: 'Переключение языка интерфейса: русский или английский.',
        tutorialStepSettingsTutorial: 'Обучение',
        tutorialStepSettingsTutorialDesc: 'В любой момент можно снова запустить это обучение.',
        tutorialStepSettingsShare: 'Поделиться',
        tutorialStepSettingsShareDesc: 'Поделиться приложением с друзьями.',
        tutorialStepTodayGoals: 'Цели на сегодня',
        tutorialStepTodayGoalsDesc: 'Список целей, которые вы взяли на сегодня. Отмечайте выполненные — так копятся очки и серия. Цели можно брать во вкладке «Цели».',
        tutorialStepGenerate: 'Отчёт за день',
        tutorialStepGenerateDesc: 'Кнопка создаёт текстовый отчёт по вашим целям за сегодня. Удобно скопировать и отправить себе в заметки или поделиться результатом.',
        tutorialStepCalendar: 'Календарь',
        tutorialStepCalendarDesc: 'Календарь показывает вашу активность по дням: чем ярче ячейка, тем больше вы сделали в этот день. Помогает видеть прогресс за недели и месяцы.',
        tutorialStepGoalsTab: 'Страница целей',
        tutorialStepGoalsTabDesc: 'Нажмите на эту кнопку, чтобы перейти на страницу с целями. Там вы сможете посмотреть завершённые цели, цели в процессе и доступные для взятия.',
        tutorialGoalsIntroTitle: 'Страница целей',
        tutorialGoalsIntroDesc: 'Здесь вы можете взять себе новые цели, посмотреть цели в процессе и уже выполненные, а также удалить цели, которые вам больше не нужны.',
        tutorialGoalsCompletedTitle: 'Завершённые',
        tutorialGoalsCompletedDesc: 'Цели, которые вы уже выполнили. Здесь видна ваша история достижений.',
        tutorialGoalsInProgressTitle: 'В процессе',
        tutorialGoalsInProgressDesc: 'Цели, которые вы взяли и ещё выполняете. Отмечайте их выполнение на главной странице.',
        tutorialGoalsAvailableTitle: 'Доступные',
        tutorialGoalsAvailableDesc: 'Цели, которые можно взять на себя. Выберите категорию ниже и нажмите на цель, чтобы взять её на 30, 60 или 120 дней.',
        tutorialGoalsChooseCategoryTitle: 'Категории целей',
        tutorialGoalsChooseCategoryDesc: 'Вот такие категории целей есть: спорт, дисциплина, духовность, саморазвитие. Выберите категорию, из которой хотите взять цель — нажмите на неё.',
        tutorialGoalsSportTitle: 'Спорт',
        tutorialGoalsSportDesc: 'Цели, связанные с физической активностью: тренировки, бег, зарядка и т.д.',
        tutorialGoalsDisciplineTitle: 'Дисциплина',
        tutorialGoalsDisciplineDesc: 'Цели для развития дисциплины: режим, привычки, самоорганизация.',
        tutorialGoalsSpiritualityTitle: 'Духовность',
        tutorialGoalsSpiritualityDesc: 'Цели для внутреннего развития: медитация, практики, рефлексия.',
        tutorialGoalsSelfDevelopmentTitle: 'Саморазвитие',
        tutorialGoalsSelfDevelopmentDesc: 'Цели для обучения и роста: чтение, курсы, навыки.',
        tutorialNext: 'Далее',
        tutorialPrev: 'Назад',
        tutorialSkip: 'Пропустить',
        tutorialDone: 'Понятно',
        tutorialStepTakeGoal: 'Выберите цель которую хотите',
        tutorialStepTakeGoalDesc: '',
        tutorialStepToastTitle: 'Вот тут будут показываться сообщения',
        tutorialStepToastDesc: '',
        tutorialStepCreateGoal: 'Создать свою цель',
        tutorialStepCreateGoalDesc: 'Нажмите кнопку «+». Заполните название и выберите категорию, затем нажмите «Добавить». Цель появится в списке доступных, и вы сможете взять её так же, как цель из списка.',
        tutorialStepCompleteGoal: 'Выполнить цель',
        tutorialStepCompleteGoalDesc: 'Вернитесь на главную. В блоке «Цели на сегодня» нажмите на цель в процессе — она отметится как выполненная, вы получите очки.',
        tutorialStepDeleteGoal: 'Удалить цель',
        tutorialStepDeleteGoalDesc: 'На странице целей во вкладке «В процессе» или «Завершённые» удерживайте карточку цели около секунды — появится кнопка «Убрать цель».',
        tutorialStepAchievementsTab: 'Страница достижений',
        tutorialStepAchievementsTabDesc: 'Нажмите на эту кнопку, чтобы перейти к достижениям. Там вы увидите свои награды за выполнение целей.',
        tutorialGoalModalChooseDays: 'Выберите насколько дней вы хотите себе взять эту цель',
        tutorialGoalModalClickButton: 'Нажмите на кнопку',
        tutorialGoalFirstTaken: 'Вы взяли свою первую цель!',
        tutorialAchievementsIntroTitle: 'Страница достижений',
        tutorialAchievementsIntroDesc: 'Здесь отображаются ваши награды за выполнение целей и прогресс. Достижения дают очки и открываются по условиям.',
        tutorialAchievementsEarnedTitle: 'Мои достижения',
        tutorialAchievementsEarnedDesc: 'Здесь показаны уже полученные вами достижения.',
        tutorialAchievementsAllTitle: 'Все достижения',
        tutorialAchievementsAllDesc: 'Здесь все достижения приложения. Можно фильтровать по редкости.',
        tutorialAchievementsRaritiesTitle: 'Редкость',
        tutorialAchievementsRaritiesDesc: 'Редкость влияет на сложность и ценность достижения: обычная, редкая, легендарная, эпическая.',
        tutorialAchievementsCardsTitle: 'Карточки достижений',
        tutorialAchievementsCardsDesc: 'Нажмите на карточку, чтобы увидеть детали и условие получения. Полученные отмечены галочкой.',
        tutorialDoneFinal: 'Вы прошли обучение',
    },
    en: {
        // Settings
        settings: 'Settings',
        darkTheme: 'Dark theme',
        lightTheme: 'Light theme',
        help: 'Help',
        color: 'Color',
        language: 'Change language',
        tutorial: 'Take tutorial',
        share: 'Share',
        selectColor: 'Select color',
        close: 'Close',
        
        // Profile
        pts: 'pts',
        todayGoals: 'Today\'s goals',
        generate: 'Generate',
        yesterday: 'Yesterday',
        series: 'Series',
        days: 'days',
        
        // Goals
        goals: 'Goals',
        completed: 'Completed',
        inProgress: 'In progress',
        available: 'Available',
        sport: 'Sport',
        discipline: 'Discipline',
        spirituality: 'Spirituality',
        selfDevelopment: 'Self-development',
        
        // Achievements
        myAchievements: 'My',
        allAchievements: 'All',
        common: 'Common',
        rare: 'Rare',
        legendary: 'Legendary',
        epic: 'Epic',
        
        // General
        copy: 'Copy',
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        ready: 'Ready!',
        generating: 'Generating report',
        reportCopied: 'Report copied!',
        loadingUser: 'Loading user data...',
        loadingGoals: 'Loading user goals...',
        loadingAchievements: 'Loading user achievements...',
        yesterdayGoals: 'Yesterday\'s goals',
        generateReport: 'Generate report',
        completingGoal: 'Completing goal...',
        goalCompleted: 'Goal completed successfully!',
        cancelingGoal: 'Canceling goal completion...',
        goalCanceled: 'Completion canceled successfully!',
        goalError: 'Error completing goal:',
        goalErrorRetry: 'Failed to complete goal. Please try again.',
        goalMoveError: 'Error moving goal:',
        goalMoveErrorRetry: 'Failed to move goal to \'In progress\'. Please try again.',
        rollback: 'Rollback',
        back: 'Back',
        noGoalsYesterday: 'You have no such goals',
        goalMoved: 'Goal successfully moved to \'In progress\'!',
        goalRemoved: 'Goal successfully removed!',
        goalRemoveError: 'Error removing goal:',
        goalRemoveErrorRetry: 'Failed to remove goal. Please try again.',
        takingGoal: 'Taking goal...',
        goalTaken: 'Goal successfully taken for',
        goalTakenDays: 'days!',
        goalTakeError: 'Error taking goal:',
        goalTakeErrorRetry: 'Failed to take goal. Please try again.',
        // ModalWindowNewGoals
        addCustomGoal: 'Add your own goal',
        addCustomGoalInfo: 'By filling in all fields, you can add your own goal that will only be yours',
        goalTitle: 'Goal title',
        goalTitlePlaceholder: 'Enter goal title',
        goalCategory: 'Goal category',
        adding: 'Adding...',
        addGoal: 'Add goal',
        addGoalError: 'Error adding goal:',
        addGoalErrorRetry: 'Failed to add goal. Please try again.',
        // ModalWindowMe
        openInTelegram: 'Open Mini App in Telegram',
        noData: 'No data',
        cardReady: 'Card ready!',
        generationError: 'Generation error',
        generateCard: 'Generate card',
        telegramApiNotFound: 'Telegram API not found',
        preparingImage: 'Preparing image for Stories...',
        uploadFailed: 'Failed to upload',
        noUploadTempUrl: 'No uploadTempUrl',
        storiesOpened: 'Stories window opened with button!',
        storiesUnavailable: 'Stories with button unavailable. Downloading...',
        downloaded: 'Downloaded! Add to story manually and insert link as sticker',
        shareFailed: 'Failed to share to Stories',
        generatingImage: 'Generating image',
        shareStory: '📤 Share/story',
        shareCaption: 'You can also get such an achievement\nhttps://t.me/BotMotivation_TG_bot \nGo to the bot, complete your goals and get achievements',
        botName: 'Bot «Daily Achievements»',
        // LoadingScreen
        welcome: 'WELCOME,',
        warrior: 'Warrior of discipline',
        loadingGoals: 'Loading goals...',
        // About
        next: 'Next',
        // Achievements
        achievements: 'Achievements',
        newAchievement: 'You got a new achievement!',
        howToGetAchievement: 'How to get achievement:',
        achievementWillBeAdded: '• Achievement will be added automatically',
        user: 'User',
        // Goals
        noSuchGoals: 'You have no such goals',
        removeGoal: 'Remove goal',
        takeGoalFor: 'Take goal for',
        days120: '120 days',
        days60: '60 days',
        days30: '30 days',
        // Lights / Milestones
        seriesFire: 'Series fire',
        continue: 'Continue',
        milestone2Title: 'Series started!',
        milestone2Subtitle: 'Try not to lose it',
        milestone5Title: 'You\'re in rhythm 👏',
        milestone5Subtitle: 'Keep up the pace',
        milestone10Title: 'Well done!',
        milestone10Subtitle: 'You\'ve been keeping the series for 10 days',
        milestone30Title: 'It\'s already a habit',
        milestone30Subtitle: '30 days in a row — seriously',
        milestone60Title: 'Stability 🔥',
        milestone60Subtitle: 'You\'re on another level',
        milestone100Title: 'Legendary',
        milestone100Subtitle: '100 days — that\'s powerful',
        milestone120Title: 'Absolute discipline',
        milestone120Subtitle: 'You\'re a machine',
        // Tutorial (home screen)
        tutorialIntroTitle: 'Tutorial',
        tutorialIntroDesc: 'You\'re about to take a short tutorial. You\'ll learn how to use the app, add your first goal, complete goals, generate a daily report, and see what everything is for.',
        tutorialIntroButton: 'Start tutorial',
        tutorialStepPoints: 'Points',
        tutorialStepPointsDesc: 'These are your points from completed goals. The more goals you finish, the more points you get — they show your progress and help you level up.',
        tutorialStepLevel: 'Level',
        tutorialStepLevelDesc: 'Here you see your current level and the bar to the next one. Level increases with points: complete goals regularly to climb higher.',
        tutorialStepProfile: 'Profile',
        tutorialStepProfileDesc: 'Your name and «streak» — how many days in a row you\'ve been completing goals.',
        tutorialStepSettingsButton: 'Settings button',
        tutorialStepSettingsButtonDesc: 'Tap this button to open settings. There you can change theme, language, color and more.',
        tutorialStepSettingsTheme: 'Theme',
        tutorialStepSettingsThemeDesc: 'Switch between light and dark theme. Choose what suits you.',
        tutorialStepSettingsHelp: 'Help',
        tutorialStepSettingsHelpDesc: 'Opens the Telegram bot for support and questions.',
        tutorialStepSettingsColor: 'Color',
        tutorialStepSettingsColorDesc: 'Choose the accent color of the app — buttons and highlights will use this color.',
        tutorialStepSettingsColorChoose: 'Choose the color you like.',
        tutorialStepSettingsLanguage: 'Language',
        tutorialStepSettingsLanguageDesc: 'Switch interface language: Russian or English.',
        tutorialStepSettingsTutorial: 'Tutorial',
        tutorialStepSettingsTutorialDesc: 'You can run this tutorial again anytime.',
        tutorialStepSettingsShare: 'Share',
        tutorialStepSettingsShareDesc: 'Share the app with friends.',
        tutorialStepTodayGoals: 'Today\'s goals',
        tutorialStepTodayGoalsDesc: 'The list of goals you took for today. Mark them done to earn points and keep your streak. You can pick goals in the «Goals» tab.',
        tutorialStepGenerate: 'Daily report',
        tutorialStepGenerateDesc: 'This button generates a text report of your goals for today. Handy to copy into notes or share your progress with others.',
        tutorialStepCalendar: 'Calendar',
        tutorialStepCalendarDesc: 'The calendar shows your activity by day: the brighter the cell, the more you did that day. Great for seeing progress over weeks and months.',
        tutorialStepGoalsTab: 'Goals page',
        tutorialStepGoalsTabDesc: 'Tap this button to go to the goals page. There you can see completed goals, goals in progress, and goals available to take.',
        tutorialGoalsIntroTitle: 'Goals page',
        tutorialGoalsIntroDesc: 'Here you can take new goals, view goals in progress and completed ones, and remove goals you no longer need.',
        tutorialGoalsCompletedTitle: 'Completed',
        tutorialGoalsCompletedDesc: 'Goals you have already completed. Your achievement history is here.',
        tutorialGoalsInProgressTitle: 'In progress',
        tutorialGoalsInProgressDesc: 'Goals you have taken and are still working on. Mark them done on the home page.',
        tutorialGoalsAvailableTitle: 'Available',
        tutorialGoalsAvailableDesc: 'Goals you can take on. Choose a category below and tap a goal to take it for 30, 60, or 120 days.',
        tutorialGoalsChooseCategoryTitle: 'Goal categories',
        tutorialGoalsChooseCategoryDesc: 'Here are the goal categories: sport, discipline, spirituality, self-development. Choose which category you want to take a goal from — tap on it.',
        tutorialGoalsSportTitle: 'Sport',
        tutorialGoalsSportDesc: 'Goals related to physical activity: workouts, running, exercise, etc.',
        tutorialGoalsDisciplineTitle: 'Discipline',
        tutorialGoalsDisciplineDesc: 'Goals for building discipline: routine, habits, self-organization.',
        tutorialGoalsSpiritualityTitle: 'Spirituality',
        tutorialGoalsSpiritualityDesc: 'Goals for inner growth: meditation, practices, reflection.',
        tutorialGoalsSelfDevelopmentTitle: 'Self-development',
        tutorialGoalsSelfDevelopmentDesc: 'Goals for learning and growth: reading, courses, skills.',
        tutorialNext: 'Next',
        tutorialPrev: 'Back',
        tutorialSkip: 'Skip',
        tutorialDone: 'Got it',
        tutorialStepTakeGoal: 'Choose the goal you want',
        tutorialStepTakeGoalDesc: '',
        tutorialStepToastTitle: 'Messages will be shown here',
        tutorialStepToastDesc: '',
        tutorialStepCreateGoal: 'Create your own goal',
        tutorialStepCreateGoalDesc: 'Tap the «+» button. Fill in the title and choose a category, then tap «Add goal». The goal will appear in the available list, and you can take it just like a preset goal.',
        tutorialStepCompleteGoal: 'Complete a goal',
        tutorialStepCompleteGoalDesc: 'Return to the main page. In the «Today\'s goals» block, tap a goal in progress — it will be marked as completed and you\'ll earn points.',
        tutorialStepDeleteGoal: 'Remove a goal',
        tutorialStepDeleteGoalDesc: 'On the goals page, in the «In progress» or «Completed» tab, hold the goal card for about a second — the «Remove goal» button will appear.',
        tutorialStepAchievementsTab: 'Achievements page',
        tutorialStepAchievementsTabDesc: 'Tap this button to go to achievements. There you\'ll see your rewards for completing goals.',
        tutorialGoalModalChooseDays: 'Choose for how many days you want to take this goal',
        tutorialGoalModalClickButton: 'Click the button',
        tutorialGoalFirstTaken: 'You\'ve taken your first goal!',
        tutorialAchievementsIntroTitle: 'Achievements page',
        tutorialAchievementsIntroDesc: 'Here you see your rewards for completing goals and your progress. Achievements give points and unlock by meeting conditions.',
        tutorialAchievementsEarnedTitle: 'My achievements',
        tutorialAchievementsEarnedDesc: 'Achievements you have already earned are shown here.',
        tutorialAchievementsAllTitle: 'All achievements',
        tutorialAchievementsAllDesc: 'All app achievements are listed here. You can filter by rarity.',
        tutorialAchievementsRaritiesTitle: 'Rarity',
        tutorialAchievementsRaritiesDesc: 'Rarity affects difficulty and value: common, rare, legendary, epic.',
        tutorialAchievementsCardsTitle: 'Achievement cards',
        tutorialAchievementsCardsDesc: 'Tap a card to see details and how to earn it. Earned ones are marked with a check.',
        tutorialDoneFinal: 'You\'ve completed the tutorial',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('ru');

    useEffect(() => {
        const savedLanguage = localStorage.getItem('app-language') || 'ru';
        setLanguage(savedLanguage);
        if (typeof document !== 'undefined') {
            document.documentElement.lang = savedLanguage;
        }
    }, []);

    useEffect(() => {
        if (typeof document !== 'undefined') {
            document.documentElement.lang = language;
        }
    }, [language]);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('app-language', lang);
    };

    const t = (key) => {
        const val = translations[language]?.[key] ?? translations.ru?.[key];
        return (val !== undefined && val !== null) ? val : key;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};
